tasks:
  # This task is run during pre-build and it's log and built results are
  # restored as part of the workspace initialization.
  - prebuild: build/gitpod/build-wasm.sh
    command: |
      sudo apt install ca-certificates gnupg
      sudo gpg --homedir /tmp --no-default-keyring --keyring /usr/share/keyrings/mono-official-archive-keyring.gpg --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 3FA7E0328081BFF6A14DA29AA6A19B38D3D831EF
      echo "deb [signed-by=/usr/share/keyrings/mono-official-archive-keyring.gpg] https://download.mono-project.com/repo/ubuntu stable-focal main" | sudo tee /etc/apt/sources.list.d/mono-official-stable.list
      sudo apt update
      sudo apt upgrade
      sudo apt install mono-devel
      sudo apt install mono-complete
      mono --version